api_timer:
  resource: "@AppBundle/Controller/Api/TimerController.php"
  type: rest
  prefix: /time

api_worker:
  resource: "@AppBundle/Controller/Api/UserController.php"
  type: rest
  prefix: /user

api_team:
  resource: "@AppBundle/Controller/Api/TeamController.php"
  type: rest
  prefix: /team

api_user_team:
  resource: "@AppBundle/Controller/Api/UserTeamController.php"
  type: rest
  prefix: /user/team

api_project:
  resource: "@AppBundle/Controller/Api/ProjectController.php"
  type: rest
  prefix: /project