NelmioApiDocBundle:
  resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
  prefix:   /api/doc

api_backend:
  resource: "routing_api.yml"
  type: rest
  prefix: /api

management:
  resource: "routing_management.yml"
  prefix: /kierownik

admin:
  resource: "routing_administration.yml"
  prefix: /admin

homepage:
  path: /
  defaults: { _controller: AppBundle:Default:index }

timer:
  path: /czasomierz
  defaults: { _controller: AppBundle:Timer:index }

administration_config:
  path: /config
  defaults: { _controller: AppBundle:Administration:index }

employee:
  path: /pracownicy
  defaults: { _controller: AppBundle:Employee:index }

projects:
  path: /projekty
  defaults: { _controller: AppBundle:Project:index }

