api_timer:
  resource: "@AppBundle/Controller/Api/TimerController.php"
  type: rest
  prefix: /time

api_worker:
  resource: "@AppBundle/Controller/Api/UserController.php"
  type: rest
  prefix: /user