NelmioApiDocBundle:
  resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
  prefix:   /api/doc

api_backend:
  resource: "routing_api.yml"
  type: rest
  prefix: /api

management:
  resource: "routing_management.yml"
  prefix: /management

admin:
  resource: "routing_administration.yml"
  prefix: /admin

homepage:
  path: /
  defaults: { _controller: AppBundle:Default:index }

timer:
  path: /czasomierz
  defaults: { _controller: AppBundle:Timer:index }

administration_config:
  path: /config
  defaults: { _controller: AppBundle:Configuration:index }

employee:
  path: /pracownicy
  defaults: { _controller: AppBundle:Employee:index }

projects:
  path: /projects
  defaults: { _controller: AppBundle:Project:index }

project_show:
  path: /project/{id}
  defaults: { _controller: AppBundle:Project:show }

specific_task:
  path: /task/{id}
  defaults: { _controller: AppBundle:Task:show }
  requirements:
    id: '\d+'

post:
  path: /wiki
  defaults: { _controller: AppBundle:Wiki:index }

post_new:
  path: /wiki/post/new
  defaults: { _controller: AppBundle:Wiki:new }

post_show:
  path: /wiki/post/{id}
  defaults: { _controller: AppBundle:Wiki:show }

post_edit:
  path: /wiki/post/{id}/edit
  defaults: { _controller: AppBundle:Wiki:edit }

post_delete:
  path: /wiki/post/delete/{id}
  defaults: { _controller: AppBundle:Wiki:deleteById }

post_bulk_action:
  path: /wiki/post/bulk-action
  defaults: { _controller: AppBundle:Wiki:bulk }

vacation_calendar:
  path: /calendar
  defaults: { _controller: AppBundle:Vacation:calendar }

vacations:
  path: /calendar/my-vacations
  defaults: { _controller: AppBundle:Vacation:userIndex }

vacation_new:
  path: /calendar/new
  defaults: { _controller: AppBundle:Vacation:new }

vacation_edit:
  path: /calendar/{id}/edit
  defaults: { _controller: AppBundle:Vacation:edit }

vacation_delete:
  path: /calendar/{id}/delete
  defaults: { _controller: AppBundle:Vacation:deleteById }