NelmioApiDocBundle:
  resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
  prefix:   /api/doc

api_backend:
  resource: "routing_api.yml"
  type: rest
  prefix: /api

management:
  resource: "routing_management.yml"
  prefix: /management

admin:
  resource: "routing_administration.yml"
  prefix: /admin

homepage:
  path: /
  defaults: { _controller: AppBundle:Default:index }

timer:
  path: /czasomierz
  defaults: { _controller: AppBundle:Timer:index }

administration_config:
  path: /config
  defaults: { _controller: AppBundle:Configuration:index }

employee:
  path: /pracownicy
  defaults: { _controller: AppBundle:Employee:index }

projects:
  path: /projekty
  defaults: { _controller: AppBundle:Project:index }

specific_task:
  path: /task/{id}
  defaults: { _controller: AppBundle:Task:show }
  requirements:
    id: '\d+'

post:
  path: /post
  defaults: { _controller: AppBundle:Wiki:index }

post_show:
  path: /post/{id}
  defaults: { _controller: AppBundle:Wiki:show }

post_new:
  path: /post/new
  defaults: { _controller: AppBundle:Wiki:new }

post_edit:
  path: /post/{id}/edit
  defaults: { _controller: AppBundle:Wiki:edit }

post_delete:
  path: /post/delete/{id}
  defaults: { _controller: AppBundle:Wiki:deleteById }

post_bulk_action:
  path: /post/bulk-action
  defaults: { _controller: AppBundle:Wiki:bulk }